[package]
name = "torro"
description = "A correct and easy-to-use BitTorrent library"
repository = "https://github.com/owez/torro"
version = "0.0.0"
authors = ["Owez <root@ogriffiths.com>"]
edition = "2018"
